notify_job:
  script: "APP=battle APP_TYPE=elixir DOCKER_IMAGE_VERSION=1.12.3-otp24 python3.7 /home/gitlab-runner/ejoyplatform_battlenet_build/main.py"
  only:
    - /^battle-\d{12}$/
    - /^battle-dev$/
    - /^battle-\d{12}-kun$/
    - /^battle-dev-kun$/
